---
apiVersion: v1
kind: Namespace
metadata:
  name: college-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-appdeployment
  labels:
    app: college-app
  namespace: college-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: college-app
  template:
    metadata:
      labels:
        app: college-app
    spec:
      containers:
      - name: python-image
        image: yashwanthkotha/python-image:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: college-appservice
  namespace: college-app
spec:
  selector:
    app: college-app
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer